### ISSUE TITLE
Error when running the plugin from command line

### ISSUE THREAD

**Issue by edimusxero** [Arelle/EdgarRenderer#3]
When I run the following command from the command line

**python3.4 arelleCmdLine.py -f "/tmp/test.zip" -o "/tmp/out.zip" --plugins 'EdgarRenderer|validate/EFM|transforms/SEC.py' --logFile edgar.log --disclosureSys**

It returns the following error 

**TypeError: edgarRendererFilingEnd() takes 3 positional arguments but 4 were given**

The output zip file is created but corrupted (can open it by other means but not with unzip)

Suggestions?

Here's the Traceback 

`Traceback (most recent call last):
  File "arelleCmdLine.py", line 17, in <module>
    CntlrCmdLine.main()

  File "/usr/local/src/dqc_us_rules/src/arelle/arelle/CntlrCmdLine.py", line 47, in main
    parseAndRun(args)
  File "/usr/local/src/dqc_us_rules/src/arelle/arelle/CntlrCmdLine.py", line 425, in parseAndRun
    cntlr.run(options)

  File "/usr/local/src/dqc_us_rules/src/arelle/arelle/CntlrCmdLine.py", line 985, in run
    pluginXbrlMethod(self, options, filesource, _entrypointFiles, sourceZipStream=sourceZipStream, responseZipStream=responseZipStream)

  File "/usr/local/src/dqc_us_rules/src/arelle/arelle/plugin/validate/EFM/__init__.py", line 311, in filingEnd
    pluginXbrlMethod(cntlr, options, filesource, modelManager.efmFiling)
TypeError: edgarRendererFilingEnd() takes 3 positional arguments but 4 were given`

**Comment by stevejneal** [comment]
Your whole command line did not paste correctly. I am assuming you have --disclosureSystem efm-pragmatic at the end. If so try changing the single quotes on the plugins to double quotes

**Comment by edimusxero** [comment]
Yes, changing to double quotes on the following command produces the same response

python3.4 arelleCmdLine.py -f "/tmp/test.zip" -o "/tmp/out.zip" --plugins "EdgarRenderer|validate/EFM|transforms/SEC.py" --logFile edgar.log --disclosureSystem efm-pragmatic


Thanks

**Comment by edimusrex** [comment]
Any update on this error?  It happens in both Ubuntu and CentOS

**Comment by edimusrex** [comment]
We finally got it running.  We needed to run this command

`perl -p -i -e 's/cntlr, options, filesource, modelManager\.efmFiling/cntlr, options, modelManager.efmFiling/' "$ARELLE_SRC/arelle/plugin/validate/EFM/__init__.py`

Removing the filesource arg from the call fixed the issue.  It now runs as expected.

**Comment by md-nadeemkhan** [comment]
Hi guys,
Are you running this plugin locally or inside arelle application? I am not able to get my head around this and has been struggling for days.. . Can you please help me out with installation steps... 

Installation steps I found on arelle site is not detailed and I couldn't complete those as explained.

Thanks
